src/Entity/Produits.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass="App\Repository\ProduitsRepository")
 * @ORM\Table(name="produits", indexes={@ORM\Index(columns={"nom", "description"}, flags={"fulltext"}) })
 */
class Produits
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2)
     */
    private $prix;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $images = [];

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Categorie", inversedBy="produits")
     * @ORM\JoinColumn(nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Options", inversedBy="produits")
     * @ORM\JoinColumn(nullable=true)
     */
    private $options;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\PanierProduit", mappedBy="produits")
     */
    private $panierProduits;

    /**
     * @ORM\Column(type="json", nullable=true)
     */
    private $colors = [];

    /**
     * @ORM\Column(type="json", nullable=true)
     * @Assert\NotBlank
     */
    private $tailles = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_choisi;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\OptionGroupe", inversedBy="produits")
     */
    private $optionGroupe;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\User", inversedBy="favoris")
     */
    private $favoris;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $inCart;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $count;

    /**
     * @ORM\Column(type="decimal", precision=10, scale=2, nullable=true)
     */
    private $total;

    public function __construct()
    {
        $this->panierProduits = new ArrayCollection();
        $this->favoris = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getImages(): ?array
    {
        return $this->images;
    }

    public function setImages(?array $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->categorie;
    }

    public function setCategorie(?Categorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getOptions(): ?Options
    {
        return $this->options;
    }

    public function setOptions(?Options $options): self
    {
        $this->options = $options;

        return $this;
    }

    /**
     * @return Collection|PanierProduit[]
     */
    public function getPanierProduits(): Collection
    {
        return $this->panierProduits;
    }

    public function addPanierProduit(PanierProduit $panierProduit): self
    {
        if (!$this->panierProduits->contains($panierProduit)) {
            $this->panierProduits[] = $panierProduit;
            $panierProduit->setProduits($this);
        }

        return $this;
    }

    public function removePanierProduit(PanierProduit $panierProduit): self
    {
        if ($this->panierProduits->contains($panierProduit)) {
            $this->panierProduits->removeElement($panierProduit);
            // set the owning side to null (unless already changed)
            if ($panierProduit->getProduits() === $this) {
                $panierProduit->setProduits(null);
            }
        }

        return $this;
    }

    public function getColors(): ?array
    {
        return $this->colors;
    }

    public function setColors(?array $colors): self
    {
        $this->colors = $colors;

        return $this;
    }

    public function getTailles(): ?array
    {
        return $this->tailles;
    }

    public function setTailles(?array $tailles): self
    {
        $this->tailles = $tailles;

        return $this;
    }

    public function getImageChoisi(): ?string
    {
        return $this->image_choisi;
    }

    public function setImageChoisi(?string $image_choisi): self
    {
        $this->image_choisi = $image_choisi;

        return $this;
    }

    public function getOptionGroupe(): ?OptionGroupe
    {
        return $this->optionGroupe;
    }

    public function setOptionGroupe(?OptionGroupe $optionGroupe): self
    {
        $this->optionGroupe = $optionGroupe;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getFavoris(): Collection
    {
        return $this->favoris;
    }

    public function addFavori(User $favori): self
    {
        if (!$this->favoris->contains($favori)) {
            $this->favoris[] = $favori;
        }

        return $this;
    }

    public function removeFavori(User $favori): self
    {
        if ($this->favoris->contains($favori)) {
            $this->favoris->removeElement($favori);
        }

        return $this;
    }

    public function getInCart(): ?bool
    {
        return $this->inCart;
    }

    public function setInCart(?bool $inCart): self
    {
        $this->inCart = $inCart;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(?int $count): self
    {
        $this->count = $count;

        return $this;
    }

    public function getTotal(): ?string
    {
        return $this->total;
    }

    public function setTotal(?string $total): self
    {
        $this->total = $total;

        return $this;
    }

    public function __toString()
    {
        return $this->nom;
    }

}

src/Controller/AccueilController.php
<?php

namespace App\Controller;

use App\Entity\Produits;
use App\Form\SearchProduitType;
use App\Repository\ProduitsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class AccueilController extends AbstractController
{

    /**
     * @Route("/accueil", name="accueil")
     */
    public function index()
    {

        return $this->render('accueil/index.html.twig', [
            'controller_name' => 'AccueilController',
        ]);
    }

    /*************ACCUEIL ADMIN**************** */

    /**
     * @Route("/accueil/admin", name="accueil_admin")
     */
    public function indexAdmin()
    {
        return $this->render('accueilAdmin/index.html.twig');
    }

    /*****************A PROPOS************************* */

    /**
     * @Route("/propos", name="propos")
     */
    public function propos()
    {
        return $this->render('accueil/propos.html.twig');
    }
    /*****************DETAILS************************************ */
    /**
     * @Route("/produits/cards", name="cards")
     */
    public function cards()
    {
        $produits = $this->getDoctrine()->getRepository(Produits::class)->findAll();
        return $this->render('accueil/produit.html.twig',[
            'produits' => $produits
        ]);
    }


    /***********************************VETEMENT FEMME******************************************* */

    /**
     * @Route("/robe", name="robe")
     */
    public function robe()
    {
    
        $robes = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 1
             ]);     
     
        return $this->render('accueil/produit.html.twig', [
            'produits' => $robes
        ]);
    }

    /**
     * @Route("/monteauxVesteFemme", name="monteauxVesteFemme")
     */
    public function monteauxVesteFemme(){

        $monteauxVesteFemmes = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 4
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $monteauxVesteFemmes
        ]);
    }


    /**
     * @Route("/tShirtFemme", name="tShirtFemme")
     */
    public function tShirtFemme(){
    
        $tShirtFemme = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 2
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $tShirtFemme
        ]);
    }

    /**
     * @Route("/blouses", name="blouses")
     */
    public function blouses(){
   
        $blouses = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 3
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $blouses
        ]);
    }

    /**
     * @Route("/pantalonFemme", name="pantalonFemme")
     */
    public function pantalonFemme(){

    
        $pantalonFemme = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 5
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $pantalonFemme
        ]);
    }

    /**
     * @Route("/jupes", name="jupes")
     */
    public function jupes(){

        $jupes = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 6
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $jupes
        ]);
    }

    /**
     * @Route("/shortsFemme", name="shortsFemme")
     */
    public function shortsFemme(){

        $shortsFemme = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 7
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $shortsFemme
        ]);
    }

    /**
     * @Route("/vetementsPlage", name="vetementsPlage")
     */
    public function vetementsPlage(){

        $vetementPlage = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 8
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $vetementPlage
        ]);
    }

    /*****************************CHAUSSEURS & SACS FEMME************************************ */
    /**
     * @Route("/chausseursFemme", name="chausseursFemme")
     */
    public function chausseursFemme(){

        $chausseurs = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 20
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $chausseurs
        ]);
    }

    /**
     * @Route("/sacs", name="sacs")
     */
    public function sacs(){

        $chausseurs = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 21
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $chausseurs
        ]);
    }

    /*******************************ACCESSOIRES FEMME***************************** */

    /**
     * @Route("/bijoux", name="bijoux")
     */
    public function bijoux(){

        $bijoux = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 22
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $bijoux
        ]);
    }

    /**
     * @Route("/lunettesSoliel", name="lunettesSoliel")
     */
    public function LunettesSoliel(){

        $lunettesSoliel = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 1,
            'options' => 23
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $lunettesSoliel
        ]);
    }

    /************************************HOMME******************************************** */

    /******************VETEMENT************************ */

    /**
     * @Route("/pantalonHomme", name="pantalonHomme")
     */
    public function pantalonHomme(){

        $pantalonHomme = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 5
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $pantalonHomme
        ]);
    }

    /**
     * @Route("/chemises", name="chemises")
     */
    public function chemises(){

        $chemises = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 9
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $chemises
        ]);
    }

    /**
     * @Route("/tShirtHomme", name="tShirtHomme")
     */
    public function tShirtHomme(){
    
        $tShirtHomme = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 2
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $tShirtHomme
        ]);
    }


    /**
     * @Route("/shortHomme", name="shortHomme")
     */
    public function shortHomme(){
    
        $shortHomme = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 7
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $shortHomme
        ]);
    }

    /**
     * @Route("/polos", name="polos")
     */
    public function plolos(){
    
        $polos = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 10
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $polos
        ]);
    }

    /**
     * @Route("/monteauxVesteHomme", name="monteauxVesteHomme")
     */
    public function monteauxVesteHomme(){

        $monteauxVesteHomme = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 4
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $monteauxVesteHomme
        ]);
    }

    /**
     * @Route("/maillots", name="maillots")
     */
    public function maillots(){

        $maillots = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 11
             ]);


        return $this->render('accueil/produit.html.twig', [
            'produits' => $maillots
        ]);
    }

    /***************************CHAUSSEURS&SACS ****************************** */

    /**
     * @Route("/chausseursHomme", name="chausseursHomme")
     */
    public function chausseursHomme(){

        $chausseurs = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 12
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $chausseurs
        ]);
    }

    /****************************ACCESSOIRES************************************** */

    /**
     * @Route("/accessoires", name="accessoires")
     */
    public function accessoires(){

        $accessoires = $this->getDoctrine()->getRepository(Produits::class)->findBy([
            'categorie' => 2,
            'options' => 13
             ]);

        return $this->render('accueil/produit.html.twig', [
            'produits' => $accessoires
        ]);

templates/accueil/details.html.twig
{% extends 'base.html.twig' %}

{% block title %} details {% endblock %}

{% block body %}

<div class="container">
	<div class="row mt-5">
		<div class="col-md-6">
        <form action="{{path('ajoutPanier')}}" method="POST">
            <div id="carousel_{{ produit.id }}" class="carousel slide" data-ride="carousel">

                <ol class="carousel-indicators">
                    {% for keys, image in produit.images %}
                        <li id="indicator_{{ keys }}" data-target="#carousel_{{ produit.id }}" data-slide-to="{{ keys }}" class="indicators {% if keys == 0 %}active{% endif %}"></li>
                    {% endfor %}
                </ol>

                <div class="carousel-inner">
                    {% for keys, image in produit.images %}
                        <div class="carousel-item w-100 {% if keys == 0 %}active{% endif %}" id="image_{{ keys }}"><img class="w-100" src="{{ asset('img/' ~ image) }}" alt="{{ image }}" ></div>
                    {% endfor %}
                </div>
                <a class="carousel-control-prev" data-slide="prev" href="#carousel_{{ produit.id }}" role="button">
                    <span aria-hidden="true" class="carousel-control-prev-icon"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" data-slide="next" href="#carousel_{{ produit.id }}" role="button">
                    <span aria-hidden="true" class="carousel-control-next-icon"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="col-md-4 ml-5">
            <p class="mt-5">{{produit.nom}}</p>

            {# PRIX #}
            <span class="orginal mt-5">{{produit.prix}}€</span>

            {# TAILLES #}
            <h6 class="mt-5">Tailles</h6>
                <div class="d-flex">
                    <select name="taille" class="form-control" required>
                        <option value="">choisir votre taille</option>
                            {% for taille in produit.tailles %}
                                <option value="{{taille}}">{{taille}}</option>
                            {% endfor %}
                    </select>
                </div>

                <input type="hidden" name="produit" value="{{produit.id}}">


                {# COLORS #}
                <h6 class="mt-5">Colors</h6>
                <select name="color" class="form-control" required>
                    <option value="">choisir votre coleur</option>
                        {% for color in produit.colors %}
                            <option value="{{color}}">{{color}}</option>
                        {% endfor %}
                </select>

            {# QUANTITE #}
            <h6 class="mt-5">Quantité</h6>
                <select name="quantite" class="form-control">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option vlaue="4">4</option>
                </select>


            {# DESCRIPTION #}
            <h6 class="mt-5">Description<span class="plus"><i data-id="{{ produit.id }}" class="fas fa-plus button-detail"></i></span></h6>
            <p id="produit_{{ produit.id }}" class="description">{{produit.description|striptags|slice(0, 180)}}</p>

            <div class="mt-5">
                {# <a class="btn btn-primary btn-sm text-center" href="{{ path('ajoutPanier', {'id': produit.id}) }}">Ajouter au panier</a> #}
                <button type="submit" class="btn btn-primary btn-sm text-center" data-target="#ajoutPanier_{{produit.id}}">
                    ajouter au panier
                </button> 

            </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}

<script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

    <script>

        $(document).ready(function () {

            // Affiche/masquer les détails d'un produit
            $('.description').hide();

            $('.button-detail').on('click', function() {
            let id = $(this).data('id');
            $(this).toggleClass('fa-plus');
            $(this).toggleClass('fa-minus');
            $('#produit_'+ id).toggle();
            });

     });

    </script>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>

        {# <script>
            $('.preview-item').on('mouseover', function() {
                let id = $(this).attr('id');
                $('.indicators').removeClass('active');
                $('.carousel-item').removeClass('active');

                $('#indicator_'+ id).addClass('active');
                $('#image_'+ id).addClass('active');
            });
        </script> #}


{% endblock %}

templates/accueil/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}E-commerce!{% endblock %}

{% block body %}

	<div class="container-fluid">
            <div class="image">
            </div>
	</div>

{% endblock %}

templates/accueil/produit.html.twig
{% extends 'base.html.twig' %}

{% block title %} produit {% endblock %}

{% block body %}

<div class="container">
	<div class="row justify-content-center mt-5">
		{% for produit in produits %}
			<div class="card mr-5 produit shadow" style="width: 18rem;">
				<a href="{{ path('details', {'id': produit.id}) }}">
					<img src="{{ asset('img_choisi/' ~ produit.imageChoisi ) }}" class="card-img-top" alt="{{ produit.nom }}">
				</a>
				<div class="card-body">
					<p class="text-secondary">{{ produit.nom }}</p>
					
					<p class="prix">{{ produit.prix }}€</p>

					<div class="d-flex justify-content-between">
						<a class="btn btn-primary btn-sm text-center" href="{{ path('details', {'id': produit.id}) }}">Ajouter au panier</a>
						<div>
							{# if user est connecté #}
							{% if is_granted("ROLE_USER") %}
								{% for favoris in produit.favoris %}
									{% if favoris.id == app.user.id  %}
										<a href="{{ path('produits_retrait_favoris', {id: produit.id}) }}">
											<i class="fas fa-heart"></i>
										</a>
									{% else %}
										<a href="{{ path('produits_ajout_favoris', {id: produit.id}) }}">
											<i class="far fa-heart"></i>
										</a>
									{% endif %}
								{% else %}
									<a href="{{ path('produits_ajout_favoris', {id: produit.id}) }}">
										<i class="far fa-heart"></i>
									</a>
								{% endfor %}
							{% else %}
								<i class="far fa-heart"></i>
							{% endif %}
						</div>
					</div>

				</div>
			</div>
		{% endfor %}
	</div>
</div>


{% endblock %}

templates/accueil/propos.html.twig
{% extends 'base.html.twig' %}

{% block title %} A propos {% endblock %}

{% block body %}

<div class="container page-wrap">

	<div class="text-center mt-5">
		<h2>Mes pratiques – soins</h2>
	</div>

	<p class="text-center">REIKI - SEANCE ENERGIE QUANTIQUE - MASSAGE INTUITIF - ECOUTE</p>

	<div class="row justify-content-center mt-5">

		<div class="col-md-6">
            <div class="mt-3">
                <h5>Le Cadre</h5>
                    <p>Lorsque je vous reçois, quelque soit la pratique ou le soin prévu, nous créons ensemble l'ambiance de ce moment :</p>

                    <p>Voulez-vous un fond sonore ? musical ? bruits apaisants ?</p>

                    <p>Voulez-vous l'écouter avec un casque ?</p>

                    <p>Va t'on diffuser une huile essentielle ? laquelle ?</p>
                    
                    <p>Quel tissu-plaid voulez-vous choisir pour la table de massage ?</p>

                    <p>Libre à vous de laisser venir…</p>

                    <p>peut-être voudrez-vous parler pendant la séance ? Alors faites le !</p>

                    <p>A la fin de chaque séance , après un petit débriefing, je vous proposerai de choisir une carte parmi différents sets de”cartes-oracle”et d’en découvrir la signification</p>
                    </div>
                    <div class="mt-5">

                    <h5>POURQUOI ?</h5>

                    <p>Pouvoir vivre en cohérence avec soi</p>

                    <p>Vivre une réalité qui ait du sens pour soi</p>

                    <p>Vivre en harmonie, dans sa propre harmonie</p>

                    <p>Vivre en résonance avec soi, sur la longueur d’onde qui nous est propre</p>

                    <p>Etre libre d’être ce que l’on est</p>

                    <p>Malgré ce que l’on vit, chez soi, en couple, en famille,au travail,socialement..</p>

                    <p>C’est ce à quoi on aspire tous, plus ou moins consciemment</p>

                    <p>Mais il y a des résistances … et c’est souvent sur le plan physique qu’elles se manifestent, et de cette façon elles se mettent en lumière et nous offrent la possibilité d’intervenir , comme un appel du corps à réagir</p>

                    <p>Et si on essayait simplement :</p>

                    <p>d’écouter les signaux que nos organes nous envoient et les pensées qui traversent notre esprit ?</p>

                    <p>de faire éclore son propre système de rééquilibrage ?</p>

                    <p>La liberté d’être soi-même engendre la joie, la quiétude intérieure et l’harmonie avec le monde extérieur</p>
                    </div>
                </div>

		<div class="col-md-6">
            <div class="mt-3">
                <img height="250" src="{{asset ('shooping1.jpg') }}" alt="shopping1" />
            </div>
            <div class="mt-5">
                <img height="330" src="{{asset ('shopping2.jpg') }}" alt="shopping2" />
            </div>
            <div class="mt-5">
                <img height="330" src="{{asset ('shopping3.jpg') }}" alt="shopping3" />
            </div>

        </div>
	</div>
</div>



{% endblock %}